"""add exercise_definitions table

Revision ID: 37aa95c9190b
Revises: b9735b4d85ea
Create Date: 2026-02-19 05:20:42.791773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37aa95c9190b"
down_revision: Union[str, Sequence[str], None] = "b9735b4d85ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercise_definitions_id"), "exercise_definitions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_definitions_name"),
        "exercise_definitions",
        ["name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_exercise_definitions_name"), table_name="exercise_definitions"
    )
    op.drop_index(op.f("ix_exercise_definitions_id"), table_name="exercise_definitions")
    op.drop_table("exercise_definitions")
    # ### end Alembic commands ###
