"""Integrate FastAPI-Users and update user model

Revision ID: b9735b4d85ea
Revises: 3db4f1bd66fc
Create Date: 2026-02-17 17:05:28.369690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9735b4d85ea"
down_revision: Union[str, Sequence[str], None] = "3db4f1bd66fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exercises", "workout_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("nutrition", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.alter_column("workouts", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workouts", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("users", "is_verified")
    op.drop_column("users", "is_superuser")
    op.alter_column("nutrition", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "exercises", "workout_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
