"""add created_at and updated_at to all models

Revision ID: fb6729d80e43
Revises: 27c33a6843cf
Create Date: 2026-02-19 06:46:51.067584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb6729d80e43"
down_revision: Union[str, Sequence[str], None] = "27c33a6843cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercise_definitions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "exercise_definitions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("exercises_workout_id_fkey"), "exercises", type_="foreignkey"
    )
    op.create_foreign_key(None, "exercises", "workouts", ["workout_id"], ["id"])
    op.add_column(
        "nutrition",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "nutrition",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "workouts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "workouts",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workouts", "updated_at")
    op.drop_column("workouts", "created_at")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("nutrition", "updated_at")
    op.drop_column("nutrition", "created_at")
    op.drop_constraint(None, "exercises", type_="foreignkey")
    op.create_foreign_key(
        op.f("exercises_workout_id_fkey"),
        "exercises",
        "workouts",
        ["workout_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("exercises", "updated_at")
    op.drop_column("exercises", "created_at")
    op.drop_column("exercise_definitions", "updated_at")
    op.drop_column("exercise_definitions", "created_at")
    # ### end Alembic commands ###
